apiVersion: v1
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.20.88.16-172.20.88.16
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config":"address-pools:\n- name: default\n  protocol: layer2\n  addresses:\n  - 172.20.88.16-172.20.88.16\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"config","namespace":"metallb-system"}}
  creationTimestamp: "2022-05-02T19:47:27Z"
  name: config
  namespace: metallb-system
  resourceVersion: "8617"
  selfLink: /api/v1/namespaces/metallb-system/configmaps/config
  uid: 730e1612-1e4f-452c-a262-1812c3b246bd
