apiVersion: v1
kind: Service
metadata:
  name: udpclient-svc
spec:
  selector:
    app.kubernetes.io/name: udpclient-proxy
  ports:
  - name: moxa-port
    port: 5005
    targetPort: moxa-svc
    nodePort: 31002    
    protocol: UDP
  - name: test-port
    port: 5006
    targetPort: test-svc
    protocol: UDP
    nodePort: 31001    
  type: NodePort
---    
apiVersion: apps/v1
kind: Deployment   
metadata:
  name: udpclient
spec:
  selector: 
    matchLabels:  
      app.kubernetes.io/name: udpclient-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: udpclient-proxy
    spec:
      containers:
      - name: udpclient
        image: brentgroves/udpclient:1.12
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 5005
          protocol: UDP
          name: moxa-svc
        - containerPort: 5006
          protocol: UDP
          name: test-svc
