singleuser:
  # Defines the default image
  image:
    name: jupyter/minimal-notebook
    tag: 2343e33dec46
  profileList:
    - display_name: "Mobex IS environment"
      description: "This has ETL, Manim, Python, R, and Julia kernels."
      kubespawner_override:
        image: brentgroves/jupyterhub:10
