apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
spec:
  selector:
    app.kubernetes.io/name: udpclient-proxy
  ports:
  - name: moxa-port
    port: 5005
    targetPort: moxa-svc
    nodePort: 31002    
    protocol: UDP
  - name: test-port
    port: 5006
    targetPort: test-svc
    protocol: UDP
    nodePort: 31001    
  type: NodePort