apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
  type: LoadBalancer      
