kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-storage-dir-pvc
spec:
  storageClassName: local-storage-dir
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
