# https://medium.com/bb-tutorials-and-thoughts/how-to-dockerize-the-python-rest-api-with-flask-library-d2b51dd4a0ae
# ARG UBUNTU_VER=18.04
ARG UBUNTU_VER=20.04
ARG CONDA_VER=latest
ARG OS_TYPE=x86_64
ARG PY_VER=3.10
ARG FLASK_VER=2.1.3
ARG FLASK_RESTFUL_VER=0.3.9 
ARG REQUESTS_VER=2.28.1
ARG REQUESTS_NTLM_VER=1.1.0
ARG TF_VER=2.5.0
ARG ZEEP_VER=4.1.0
ARG PYODBC_VER=4.0.32 
ARG PANDAS_VER=1.4.2
ARG SQLALCHEMY_VER=1.4.32
ARG PYTHON_CRONTAB_VER=2.6.0
ARG MARSHMALLOW_VER=3.17.0
ARG PEEWEE_VER=3.15.1

# ARG MYSQL_CONNECTOR_VER=8.0.18 use pip install mysql-connector-python could not get conda version to install
FROM ubuntu:${UBUNTU_VER}

RUN apt-get update && apt-get install -yq \
  tzdata \
  ksh \
  apt-utils \
  apt-transport-https \
  ca-certificates \
  neofetch \
  software-properties-common \
  curl \
  wget \
  dnsutils \
  iputils-ping \
  netcat \
  tree \
  curl \
  vim \
  jq \
  msmtp \
  msmtp-mta \
  mailutils \ 
  bsd-mailx \
  cron \
  && ln -fs /usr/share/zoneinfo/America/Indiana/Indianapolis /etc/localtime \
  && dpkg-reconfigure -f noninteractive tzdata  \
  && rm -rf /var/lib/apt/lists/*

# Use the above args during building https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
ARG CONDA_VER
ARG OS_TYPE
# Install miniconda to /miniconda
RUN curl -LO "http://repo.continuum.io/miniconda/Miniconda3-${CONDA_VER}-Linux-${OS_TYPE}.sh"
RUN bash Miniconda3-${CONDA_VER}-Linux-${OS_TYPE}.sh -p /miniconda -b
RUN rm Miniconda3-${CONDA_VER}-Linux-${OS_TYPE}.sh
ENV PATH=/miniconda/bin:${PATH}
RUN conda update -y conda

ARG PY_VER
ARG ZEEP_VER
ARG PYODBC_VER 
ARG PANDAS_VER
ARG SQLALCHEMY_VER
# ARG MYSQL_CONNECTOR_VER use pip install instead



# Install packages from anaconda.
RUN conda install -c anaconda -y python=${PY_VER}
RUN conda install -c anaconda -y \
    pyodbc=${PYODBC_VER} \ 
    pandas=${PANDAS_VER} \
    sqlalchemy=${SQLALCHEMY_VER} \
    flask=${FLASK_VER} \ 
    requests=${REQUESTS_VER}

# Install packages from conda-forge
RUN conda install -c conda-forge -y \
    zeep=${ZEEP_VER} \
    flask-restful=${FLASK_RESTFUL_VER} \ 
    requests_ntlm=${REQUESTS_NTLM_VER} \
    python-crontab=${PYTHON_CRONTAB_VER} \ 
    marshmallow=${MARSHMALLOW_VER} 

RUN pip install mysql-connector-python --quiet   

WORKDIR /project

COPY app.py .

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000" ]